import { test, expect } from '@playwright/test'
test('desktop navigation, service details, projects and inquiry', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('http://127.0.0.1:5173/nigh-owl/', { waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Digital Solutions')
  await page.getByRole('button', { name: 'Explore Services' }).click()
  await expect(page.getByText('Virtual assistance')).toBeVisible()
  await page.getByRole('button', { name: /Website.*Responsive/ }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.locator('.project-card').first().click()
  await expect(page.getByRole('dialog')).toContainText('FORMA')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'Start a Project', exact: true }).click()
  await page.getByLabel('Your name').fill('Test Person')
  await page.getByLabel('Email address').fill('test@example.com')
  await page.getByLabel('Tell us about your project').fill('A new website for our studio.')
  await page.getByRole('button', { name: 'Prepare my inquiry' }).click()
  await expect(page.getByText('Your project brief is ready.')).toBeVisible()
  await expect(page.locator('pre')).toContainText('Test Person')
  await page.keyboard.press('Escape')
  expect(errors).toEqual([])
})
test('mobile menu and horizontal layout', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('http://127.0.0.1:5173/nigh-owl/', { waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: 'Open menu', exact: true }).click()
  await page.locator('#mobile-nav').getByRole('link', { name: 'Services' }).click()
  await expect(page.locator('#mobile-nav')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'mobile-preview.png', fullPage: true, animations: 'disabled', timeout: 10000 })
})
