import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import ShootingStars from './ShootingStars'
import { ArrowRight, ArrowUpRight, ArrowLeft, Bot, ChartNoAxesColumnIncreasing, Check, CodeXml, Copy, Menu, Mouse, Play, Settings, Video, X } from 'lucide-react'
const currentYear = new Date().getFullYear()
const AmbientScene = lazy(() => import('./AmbientScene'))
const HeroScene = lazy(() => import('./HeroScene'))
const services = [
  { name: 'Web Development', icon: CodeXml, text: 'Modern, fast, and conversion-focused websites.', detail: 'From your first impression to your next conversion. We design and develop responsive websites, online stores, and custom web applications built around your business.', tags: ['UI / UX design', 'React development', 'E-commerce'] },
  { name: 'AI & Automation', icon: Bot, text: 'Work smarter with automations tailored to your business.', detail: 'Give your team time for the work that matters. Connect your tools, simplify repetitive tasks, and create thoughtful AI assistants for everyday operations.', tags: ['AI assistants', 'Workflow automation', 'Tool integrations'] },
  { name: 'Digital Marketing', icon: ChartNoAxesColumnIncreasing, text: 'SEO, ads, and strategies to get you noticed.', detail: 'Turn attention into meaningful growth with search strategy, focused campaigns, and clear reporting. Every decision starts with your audience and your goals.', tags: ['Search optimization', 'Paid campaigns', 'Analytics'] },
  { name: 'Content & Media', icon: Video, text: 'Photos, videos, and visuals that tell your story.', detail: 'Make people stop, feel, and remember. Bring your brand to life through considered photography, cinematic video, and content made for the channels you use.', tags: ['Video production', 'Photography', 'Social content'] },
  { name: 'Business Solutions', icon: Settings, text: 'Systems, CRM, and digital tools to improve efficiency.', detail: 'Build a better way to work. Bring your customer relationships, internal processes, and business data together with systems tailored to your team.', tags: ['CRM systems', 'Custom dashboards', 'Digital consulting'] },
]
const projects = [
  { name: 'Elevating brands online.', brand: 'FORMA', category: 'Web Development', type: 'web', description: 'A concept digital flagship for an architecture studio. Editorial typography and a considered portfolio make the work the hero.' },
  { name: 'Less busywork. More possibility.', brand: 'FLOWSTATE', category: 'AI & Automation', type: 'automation', description: 'An automation dashboard concept that connects everyday tools and gives teams a clear picture of their workflows.' },
  { name: 'Content that captures attention.', brand: 'AFTER HOURS', category: 'Content & Media', type: 'media', description: 'A cinematic campaign direction exploring light, movement, and the creative energy of the city after dark.' },
  { name: 'Built for your next chapter.', brand: 'MERIDIAN', category: 'Business Solutions', type: 'business', description: 'A business platform concept combining customer insights, performance reporting, and a focused workspace.' },
]
function Brand() {
  return <a className="brand supplied-brand" href="#home" aria-label="NightOwls Media & Solutions home">
    <img className="supplied-logo" src="/images/nightowls-logo.jpg" alt="NightOwls Media & Solutions" width={1280} height={1280} />
  </a>
}
function Modal({ children, onClose, title }: { children: ReactNode; onClose: () => void; title: string }) {
  const ref = useRef<HTMLDialogElement>(null)
  useEffect(() => { const el = ref.current!; el.showModal(); const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = old; el.close() } }, [])
  return <dialog ref={ref} className="modal" aria-label={title} onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose() }}><div className="modal-inner"><button className="close-button" onClick={onClose} aria-label="Close dialog"><X size={22} /></button>{children}</div></dialog>
}
function ProjectVisual({ type, brand }: { type: string; brand: string }) {
  return <div className={`project-art ${type}`} aria-hidden="true">
    {type === 'web' ? <div className="mock-browser"><div className="mock-nav">{brand}<span>Architecture & spaces ?</span></div><div className="architecture"><div className="arch-block" /><p>Spaces for<br /><i>living well.</i></p></div></div>
    : type === 'automation' ? <div className="flow-art"><span className="flow-label">{brand} / WORKSPACE</span><div className="flow-node"><Bot size={22} /><span>Your workflow.<small>On autopilot.</small></span><span className="status-dot" /></div><div className="flow-lines" /><div className="flow-tools"><span><CodeXml size={19} /></span><span><Settings size={19} /></span><span><ChartNoAxesColumnIncreasing size={19} /></span></div><div className="flow-stat">24.8<span>hours saved this week</span></div></div>
    : type === 'media' ? <div className="media-art"><div className="spotlight" /><div className="camera-body"><div className="camera-lens" /><span>NO / 24</span></div><span className="media-word">AFTER<br /><i>HOURS.</i></span></div>
    : <div className="mock-browser business-screen"><div className="mock-nav">{brand}<span>YOUR BUSINESS, CONNECTED.</span></div><p>Clarity. In every detail.</p><div className="dashboard"><div><small>Business overview</small><strong>Moving forward ?</strong><div className="chart-bars">{[25,40,32,62,50,73,67,96].map((h,i)=><i key={i} style={{height: `${h}%`}} />)}</div></div><div className="dashboard-side"><span>Performance</span><b>+28.6%</b><span>Projects</span><b>24</b></div></div></div>}
  </div>
}
function ContactForm() {
  const [brief, setBrief] = useState('')
  const [copied, setCopied] = useState(false)
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); setBrief(`Project inquiry — NightOwls Media & Solutions\n\nName: ${data.get('name')}\nEmail: ${data.get('email')}\nService: ${data.get('service')}\n\n${data.get('message')}`) }
  return <><p className="eyebrow">YOUR NEXT CHAPTER</p><h2>Let’s make it happen.</h2><p className="modal-copy">Tell us a little about your idea. Great things start with a conversation.</p>{brief ? <div className="brief-result"><Check size={28} /><h3>Your project brief is ready.</h3><p>This preview doesn’t send inquiries yet. Copy or download your brief to keep it.</p><pre>{brief}</pre><div className="flex flex-wrap gap-3"><button className="button button-light" onClick={async () => { try { await navigator.clipboard.writeText(brief); setCopied(true) } catch { setCopied(false) } }}>{copied ? <Check size={16} /> : <Copy size={16} />}{copied ? 'Copied' : 'Copy brief'}</button><a className="button button-outline" href={`data:text/plain;charset=utf-8,${encodeURIComponent(brief)}`} download="nightowls-project-brief.txt">Download brief <ArrowRight size={16} /></a></div></div> : <form onSubmit={submit} className="contact-form"><div className="grid gap-4 sm:grid-cols-2"><label>Your name<input name="name" required autoComplete="name" placeholder="Alex Morgan" maxLength={100} /></label><label>Email address<input name="email" type="email" required autoComplete="email" placeholder="alex@company.com" /></label></div><label>What can we help with?<select name="service">{services.map(s=><option key={s.name}>{s.name}</option>)}<option>A little of everything</option></select></label><label>Tell us about your project<textarea name="message" required rows={4} maxLength={4000} placeholder="The idea, the ambition, the what-if…" /></label><button className="button button-light" type="submit">Prepare my inquiry <ArrowUpRight size={17} /></button><p className="form-note">Preview form · Your details stay in this browser.</p></form>}</>
}
export default function App() {
  const [menu, setMenu] = useState(false)
  const [modal, setModal] = useState<'contact' | 'reel' | null>(null)
  const [service, setService] = useState<number | null>(null)
  const [project, setProject] = useState<number | null>(null)
  const [allServices, setAllServices] = useState(false)
  const [reelIndex, setReelIndex] = useState(0)
  const [active, setActive] = useState('home')
  const workRef = useRef<HTMLDivElement>(null)
  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id) }), { rootMargin: '-15% 0px -55% 0px' })
    document.querySelectorAll('section[id]').forEach(el => observer.observe(el)); return () => observer.disconnect()
  }, [])
  useEffect(() => { if (modal !== 'reel') return; const id = window.setInterval(() => setReelIndex(i => (i + 1) % projects.length), 4500); return () => clearInterval(id) }, [modal])
  const contact = () => { setMenu(false); setService(null); setProject(null); setModal('contact') }
  return <div className="site-shell"><ShootingStars /><a className="skip-link" href="#main">Skip to content</a>
    <header className="header"><div className="container header-inner"><Brand /><nav className="desktop-nav" aria-label="Main navigation">{[['home','Home'],['services','Services'],['work','Our Work'],['about','About']].map(([id,label])=><a className={active===id?'active':''} key={id} href={`#${id}`}>{label}</a>)}<button onClick={contact}>Contact</button></nav><div className="header-actions"><button className="button button-outline header-cta" onClick={contact}>Let’s Talk <ArrowUpRight size={16} /></button><button className="menu-button" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} aria-controls="mobile-nav" onClick={()=>setMenu(!menu)}>{menu?<X size={22}/>:<Menu size={22}/>}</button></div></div>{menu && <nav id="mobile-nav" className="mobile-nav" aria-label="Expanded navigation">{[['home','Home'],['services','Services'],['work','Our Work'],['about','About']].map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}<ArrowUpRight size={17}/></a>)}<button onClick={contact}>Start a conversation <ArrowRight size={17}/></button></nav>}</header>
    <main id="main"><section id="home" className="hero"><div className="ambient-scene" aria-hidden="true"><Suspense fallback={null}><AmbientScene /></Suspense></div><div className="hero-shade" /><div className="hero-scene"><Suspense fallback={null}><HeroScene /></Suspense></div><div className="container hero-content"><p className="eyebrow">IDEAS NEVER SLEEP</p><h1>Smart<br />Digital Solutions.<br /><span>Built After Hours.</span></h1><p className="hero-description">We help businesses grow through modern websites,<br className="desktop-break" /> creative media, and smart automation — so you can<br className="desktop-break" /> focus on what matters, day or night.</p><div className="hero-buttons"><button className="button button-light" onClick={contact}>Start a Project <ArrowRight size={18}/></button><button className="reel-button" onClick={()=>setModal('reel')}><span className="play-circle"><Play size={14} fill="currentColor" /></span><span>Explore our vision<small>A creative preview</small></span></button></div><div className="hero-stats"><div><strong>Strategy.</strong><span>Purpose in every decision</span></div><div><strong>Creativity.</strong><span>Ideas that stand apart</span></div><div><strong>Technology.</strong><span>Built to move you forward</span></div></div><a className="scroll-link" href="#services"><Mouse size={25} strokeWidth={1}/><span>SCROLL TO EXPLORE</span><span className="scroll-line" /></a></div><div className="hero-side"><span>CREATIVE</span><span>STRATEGIC</span><span>AUTOMATED</span><span>ALWAYS ON</span><i /></div><div className="hero-caption">SAME VISION.<br />DIFFERENT HOURS.</div><div className="hero-bottom" /></section>
    <section id="services" className="container section services-section"><div className="section-heading"><div><p className="eyebrow">OUR SERVICES</p><h2>Everything You Need<br />to Grow Online<span className="muted">.</span></h2></div><p className="section-description">From strategy to execution, we provide end-to-end<br className="desktop-break"/> digital solutions designed for real results.</p><button className="text-link" aria-expanded={allServices} onClick={()=>setAllServices(!allServices)}>{allServices?'Less detail':'Explore Services'} <ArrowRight size={18}/></button></div><div className="services-grid">{services.map((s,i)=><button className="service-card group" key={s.name} onClick={()=>setService(i)}><s.icon size={34} strokeWidth={1.5}/><span className="service-number">0{i+1}</span><h3>{s.name}</h3><p>{s.text}</p><span className="circle-arrow"><ArrowUpRight size={16}/></span></button>)}</div>{allServices && <div className="expanded-services">{services.map(s=><div key={s.name}><h3>{s.name}</h3><p>{s.detail}</p><div className="tags">{s.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div>)}</div>}</section>
    <section id="work" className="container section work-section"><div className="section-heading"><div><p className="eyebrow">SELECTED CONCEPTS</p><h2>Good Ideas. Brought to Life<span className="muted">.</span></h2></div><p className="section-description">A glimpse of what’s possible.<br />Explore our creative and digital directions.</p><div className="carousel-controls"><button aria-label="Previous projects" onClick={()=>workRef.current?.scrollBy({left:-350,behavior:'smooth'})}><ArrowLeft size={17}/></button><button aria-label="Next projects" onClick={()=>workRef.current?.scrollBy({left:350,behavior:'smooth'})}><ArrowRight size={17}/></button></div></div><div className="project-grid" ref={workRef}>{projects.map((p,i)=><button className="project-card" key={p.brand} onClick={()=>setProject(i)}><ProjectVisual type={p.type} brand={p.brand}/><div className="project-overlay"><span className="project-index">0{i+1} / CONCEPT</span><h3>{p.name}</h3><span className="project-category">{p.category}<ArrowUpRight size={13}/></span></div><span className="project-open"><ArrowUpRight size={20}/></span></button>)}</div></section>
    <section id="about" className="container section process-section"><div className="section-heading"><div><p className="eyebrow">OUR PROCESS</p><h2>Simple. Clear. Effective<span className="muted">.</span></h2></div><p className="section-description">Big ambitions. A clear way forward.</p></div><div className="process-grid">{[['Discover','We learn about your goals and challenges.'],['Plan','We create a tailored strategy.'],['Build','We design, develop, and bring ideas to life.'],['Grow','We support and optimize for long-term success.']].map(([title,text],i)=><div className="process-step" key={title}><span className="step-number">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div>{i<3 && <ArrowRight className="step-arrow" size={17}/>}</div>)}</div></section>
    <section id="contact" className="container contact-section"><div className="contact-banner"><div><p className="eyebrow">THE NEXT GREAT IDEA COULD BE YOURS</p><h2>Let’s Build Something Great<span className="muted">.</span></h2><p>Whether you need a website, content, or a custom solution,<br className="desktop-break"/> we’re ready to make it happen.</p></div><div className="contact-action"><button className="button button-light" onClick={contact}>Get Started <ArrowRight size={18}/></button><span>A conversation. A possibility.</span></div><p className="signature">Great Ideas<br /><span>Never Sleep.</span></p></div></section></main>
    <footer className="container footer"><Brand/><p>© {currentYear} NightOwls Media & Solutions.</p><a href="#home">BACK TO TOP <ArrowUpRight size={14}/></a></footer>
    {service !== null && <Modal title={services[service].name} onClose={()=>setService(null)}><p className="eyebrow">WHAT WE DO / 0{service+1}</p><h2>{services[service].name}</h2><p className="modal-copy">{services[service].detail}</p><div className="tags">{services[service].tags.map(tag=><span key={tag}>{tag}</span>)}</div><button className="button button-light mt-8" onClick={contact}>Let’s talk about your project <ArrowRight size={17}/></button></Modal>}
    {project !== null && <Modal title={projects[project].brand} onClose={()=>setProject(null)}><p className="eyebrow">{projects[project].category} / CONCEPT PROJECT</p><h2>{projects[project].brand}</h2><div className="project-preview"><ProjectVisual type={projects[project].type} brand={projects[project].brand}/></div><p className="modal-copy">{projects[project].description}</p><button className="button button-light" onClick={contact}>Build something like this <ArrowRight size={17}/></button></Modal>}
    {modal === 'contact' && <Modal title="Start a project" onClose={()=>setModal(null)}><ContactForm/></Modal>}
    {modal === 'reel' && <Modal title="Our creative vision" onClose={()=>setModal(null)}><p className="eyebrow">THE NIGHTOWLS PERSPECTIVE</p><h2>Ideas made possible.</h2><div className="project-preview reel-preview"><ProjectVisual type={projects[reelIndex].type} brand={projects[reelIndex].brand}/></div><h3 className="reel-title">{projects[reelIndex].name}</h3><p className="modal-copy">{projects[reelIndex].description}</p><div className="reel-dots">{projects.map((p,i)=><button key={p.brand} aria-label={`Show ${p.brand}`} aria-pressed={i===reelIndex} onClick={()=>setReelIndex(i)} />)}</div><p className="form-note">Creative concept showcase</p></Modal>}
  </div>
}





